app/auth.py
from flask import Blueprint, render_template, request, flash, redirect, url_for
from .models import User
from . import db
from .forms import SignUpForm, LoginForm, ChangePasswordForm
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import login_user, login_required, logout_user, current_user


auth = Blueprint('auth', __name__)

@auth.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        email = form.email.data
        password = form.password.data

        user = User.query.filter_by(email=email).first()
        if user:
            if check_password_hash(user.password, password):
                flash('Logged in successfully!', category='success')
                login_user(user, remember=True)
                return redirect(url_for('routes.home'))
            else:
                flash('Incorrect password, try again.', category='error')
        else:
            flash('Email does not exist.', category='error')

    return render_template("login.html", user=current_user, form=form)

@auth.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('auth.login'))

@auth.route('/sign-up', methods=['GET', 'POST'])
def sign_up():
    form = SignUpForm()
    if form.validate_on_submit():
        email = form.email.data
        username = form.username.data
        password1 = form.password1.data
        is_bounty_hunter = form.is_bounty_hunter.data == 'yes'
    
        user = User.query.filter_by(email=email).first()
        if user:
            flash('Email already in use.', category='error')
        elif len(username) < 6:
            flash('Username must be longer than 5 characters.', category='error')
        elif len(password1) < 7:
            flash('Invalid password: must be at least 7 characters.', category='error')
        else:
            password_hash = generate_password_hash(password1, method='pbkdf2:sha256')
            new_user = User(email=email, username=username, password=password_hash, avatar="pfp.png", isHunter=is_bounty_hunter)
            db.session.add(new_user)
            db.session.commit()
            flash('Account created!', category='success')
            login_user(new_user, remember=True)
            return redirect(url_for('routes.home'))
    else:
        if request.method == 'POST':
            flash("Please fill out all fields correctly", category='error')

    return render_template("signup.html", user=current_user, form=form)

@auth.route('/changepassword', methods=['GET', 'POST'])
@login_required
def changepassword():
    form = ChangePasswordForm()
    if form.validate_on_submit():
        if check_password_hash(current_user.password, form.old_password.data):
            hashed_password = generate_password_hash(form.new_password.data, method='pbkdf2:sha256')
            current_user.password = hashed_password
            db.session.commit()
            flash('Password changed successfully!', category='success')
            return redirect(url_for('routes.profile'))
        else:
            flash('Invalid old password. Please try again.', category='error')
    return render_template('change-password.html', user=current_user, form=form) 

app/routes.py
from flask import Blueprint, render_template, url_for, request, flash, redirect, jsonify
from flask_login import login_required, current_user
from . import db, allowed_file, allowed_size
from .models import User, Post, Comments, Likes, Sell, Promote
from .forms import SearchForm, CommentForm, DiscussionForm, ProfileEditForm, SellForm, BountyForm
from werkzeug.utils import secure_filename
from flask_wtf import CSRFProtect
from sqlalchemy import func
import os


routes = Blueprint('routes', __name__)
@routes.route('/')
@routes.route('/home')
@routes.route('/user/<name>')
def home():
    return render_template('home.html', user=current_user)

@routes.route('/browse', methods=['GET', 'POST'])
def browse():
    form = SearchForm()
    posts = Post.query.filter_by(claimed=False).all()
    not_sold = Sell.query.filter_by(sold="Unsold").all()
    posts += not_sold  # Combine posts and not_sold

    if form.validate_on_submit():
        keyword = form.keyword.data.strip()
        if keyword:  # If keyword is not empty
            keywords = keyword.split()  # Split the keyword into individual words
            filtered_posts = []

            for post in posts:
                for kw in keywords:
                    if kw.lower() in post.title.lower():  # or kw.lower() in post.desc.lower():
                        filtered_posts.append(post)
                        break

            posts = filtered_posts
            if not filtered_posts:
                flash("No posts match your search", category='error')
        else:
            posts = Post.query.filter_by(claimed=False).all() + Sell.query.filter_by(sold="Unsold").all()  # Reset to all posts

    bounty_posts = Post.query.filter(Post.flag == "Bounty").all()
    advice_posts = Post.query.filter(Post.flag == "Discussion").all()
    weapons_posts = Sell.query.filter().all()

    lip = [like.pid for like in Likes.query.filter_by(uid=current_user.uid, liked=True).all()]
    dip = [like.pid for like in Likes.query.filter_by(uid=current_user.uid, disliked=True).all()]

    return render_template('browse.html', user=current_user, form=form, posts=posts, bounty_posts=bounty_posts, weapons_posts=weapons_posts, advice_posts=advice_posts, lip=lip, dip=dip)


@routes.route('/like_post/<int:post_id>', methods=['POST'])
def like_post(post_id):
    user_id = current_user.uid  # Assuming user_id is always present in session
    post = Post.query.get_or_404(post_id)

    like_record = Likes.query.filter_by(uid=user_id, pid=post_id).first()

    if like_record:
        if not like_record.liked:
            like_record.liked = True
            like_record.disliked = False  # Ensure a post cannot be both liked and disliked
            post.likes += 1  # Increment likes
            if post.dislikes > 0:
                post.dislikes -= 1  # Decrement dislikes if previously disliked
        else:
            like_record.liked = False  # Toggle like off if already liked
            post.likes -= 1  # Decrement likes
    else:
        like_record = Likes(uid=user_id, pid=post_id, liked=True)
        db.session.add(like_record)
        post.likes += 1  # Increment likes

    db.session.commit()
    return jsonify(success=True)


@routes.route('/dislike_post/<int:post_id>', methods=['POST'])
def dislike_post(post_id):
    user_id = current_user.uid  # Assuming user_id is always present in session
    post = Post.query.get_or_404(post_id)

    like_record = Likes.query.filter_by(uid=user_id, pid=post_id).first()

    if like_record:
        if not like_record.disliked:
            like_record.disliked = True
            like_record.liked = False  # Ensure a post cannot be both liked and disliked
            post.dislikes += 1  # Increment dislikes
            if post.likes > 0:
                post.likes -= 1  # Decrement likes if previously liked
        else:
            like_record.disliked = False  # Toggle dislike off if already disliked
            post.dislikes -= 1  # Decrement dislikes
    else:
        like_record = Likes(uid=user_id, pid=post_id, disliked=True)
        db.session.add(like_record)
        post.dislikes += 1  # Increment dislikes

    db.session.commit()
    return jsonify(success=True)

@routes.route('/post/<int:post_id>', methods=['GET', 'POST'])
def post(post_id):
    post = Post.query.get_or_404(post_id)
    comments = Comments.query.filter_by(pid=post_id).all()
    form = CommentForm()


    lip = [like.pid for like in Likes.query.filter_by(uid=current_user.uid, liked=True).all()]
    dip = [like.pid for like in Likes.query.filter_by(uid=current_user.uid, disliked=True).all()]

    if form.validate_on_submit():
        comment_text = form.comment.data
        new_comment = Comments(
            pid=post_id,
            uid=current_user.get_id(),
            comment=comment_text,
            timestamp=func.now()
        )
        db.session.add(new_comment)
        db.session.commit()
        flash('Comment Added!', category='success')


        return redirect(url_for('routes.post', post_id=post_id))

    return render_template('post.html', user=current_user, post=post, comments=comments, form=form, lip=lip, dip=dip)
@routes.route('/view-other-userpf/<int:user_id>', methods=['GET', 'POST'])
def view_userpf(user_id):
    userinfo = User.query.get_or_404(user_id)
    posts = Post.query.filter_by(uid=user_id, claimed=False).all()
    not_sold = Sell.query.filter_by(uid=user_id, sold="Unsold").all()
    posts += not_sold  # Combine posts and not_sold

    # Generate these lists based on the currently logged in user
    lip = [like.pid for like in Likes.query.filter_by(uid=current_user.get_id(), liked=True).all()]
    dip = [like.pid for like in Likes.query.filter_by(uid=current_user.get_id(), disliked=True).all()]

    promoted_by_current_user = Promote.query.filter_by(promoted_by=current_user.get_id(), promoted=True, promoting_this_guy=user_id).first()

    return render_template('view-other-userpf.html', user=current_user, userinfo=userinfo, posts=posts, promoted_by_current_user=promoted_by_current_user, lip=lip, dip=dip)



@routes.route('/promote_user/<int:user_id>', methods=['POST'])
def promote_user(user_id):
    promote_hunter = Promote.query.filter_by(promoted_by=current_user.get_id(), promoting_this_guy=user_id).first()
    hunter = User.query.get_or_404(user_id)
    
    if promote_hunter:
        if not promote_hunter.promoted:
            promote_hunter.promoted = True
            hunter.promote += 1  # Increment promotion count
        else:
            promote_hunter.promoted = False  # Toggle promotion off if already promoted
            hunter.promote -= 1  # Decrement promotion count
    else:
        promote_hunter = Promote(promoted_by=current_user.get_id(), promoting_this_guy=user_id, promoted=True)
        db.session.add(promote_hunter)
        hunter.promote += 1  # Increment promotion count
    if hunter.promote > 0:
        hunter.rank = "D"
    elif hunter.promote > 10:
        hunter.rank = "C"
    elif hunter.promote > 20:
        hunter.rank = "B"
    elif hunter.promote > 30:
        hunter.rank = "A"
    elif hunter.promote > 40:
        hunter.rank = "S"
    elif hunter.promote > 50:
        hunter.rank = "SS"
    db.session.commit()
    return jsonify(success=True, promotion_count=hunter.promote)

@routes.route('/faq')
def faq():
    return render_template('faq.html', user=current_user)

@routes.route('/ranking')
def ranking():
    highest_promoted = User.query.order_by(User.promote.desc()).all()
    print(highest_promoted)
    return render_template('ranking.html', user=current_user, highest_promoted=highest_promoted)

@routes.route('/discussion', methods=['GET', 'POST'])
def discussion():
    form = DiscussionForm()
    if form.validate_on_submit():
        title = form.title.data
        image = form.image.data
        desc = form.desc.data
        user_id = current_user.get_id()

        if image and allowed_file(image.filename):
            filename = secure_filename(image.filename)
            save_path = os.path.join('app', 'static', 'images', 'posts', filename)
            image.save(save_path)

            new_disc_post = Post(
                title=title,
                desc=desc,
                flag="Discussion",
                uid=user_id,
                img=filename
            )
            db.session.add(new_disc_post)
            db.session.commit()
            flash('Discussion Post Uploaded!', category='success')
            return redirect(url_for('routes.discussion'))
        else:
            flash("Invalid file format. PNG, JPG, JPEG accepted", category='error')

    return render_template('discussion.html', user=current_user, form=form)

@routes.route('/post/delete/<int:post_id>/<string:post_flag>', methods=['POST'])
@login_required
def delete_post(post_id, post_flag):
    if post_flag == "Discussion" or post_flag == "Bounty":
        post = Post.query.get_or_404(post_id)
        db.session.delete(post)
        db.session.commit()
        flash('Post deleted successfully', 'success')
    elif post_flag == "Listing":
        post = Sell.query.get_or_404(post_id)
        db.session.delete(post)
        db.session.commit()
        flash('Listing deleted successfully', 'success')
    # Check if the current user is the author of the post
    if post.uid != current_user.uid:
        print("lol")  # Forbidden - user is not authorized to delete this post

    db.session.delete(post)
    db.session.commit()
    flash('Post deleted successfully', 'success')
    return redirect(url_for('routes.profile'))

@routes.route('/profile')
def profile():
    user = current_user
    num_posts = Post.query.filter_by(uid=current_user.get_id(), claimed=False).count() + Sell.query.filter_by(uid=current_user.get_id(), sold="Unsold").count()
    total_likes = Post.query.filter_by(uid=current_user.get_id()).with_entities(func.sum(Post.likes)).scalar()

app/templates/change-password.html
{% extends "base.html" %} {% block title %}Change
Password{% endblock %} {% block content %}
<div class="intro-section">
	<h1 class="pagetitle-edit">Change Password</h1>
	<form method="POST">
		{{ form.hidden_tag() }}
		<div class="edit">
			<div class="form-group">
				{{ form.old_password.label }} {{
				form.old_password(class="form-input-bubble",
				placeholder="Enter old password") }} {%
				for error in form.old_password.errors %}
				<span class="text-danger"
					>{{ error }}</span
				>
				{% endfor %}
			</div>
			<br>
			<div class="form-group">
				{{ form.new_password.label }} {{
				form.new_password(class="form-input-bubble",
				placeholder="Enter new password") }} {%
				for error in form.new_password.errors %}
				<span class="text-danger"
					>{{ error }}</span
				>
				{% endfor %}
			</div>
			<br>
			<div class="form-group">
				{{ form.confirm_new_password.label }} {{
				form.confirm_new_password(class="form-input-bubble",
				placeholder="Confirm new password") }} {%
				for error in
				form.confirm_new_password.errors %}
				<span class="text-danger"
					>{{ error }}</span
				>
				{% endfor %}
			</div>
			<br>
			<input
				class="btn-submit"
				type="submit"
				value="Submit" />
		</div>
	</form>
</div>
{% endblock %}

app/templates/edit-profile.html
{% extends "base.html" %}
{% block title %}Edit profile{% endblock %}
{% block content %}
<div class="home">
  <div class="editprofile forum-section">
    <div class="row">
      <div class="col-lg-6 col-md-4 col-sm-2">
        <h1 class="star-text">Edit Profile</h1>
      </div>
      <div class="col-lg-6 col-md-8 col-sm-10">
        <!-- Profile Edit Form -->
        <form method="POST" enctype="multipart/form-data" class="form-edit">
          {{ form.hidden_tag() }}
          <div class="form-group">
            {{ form.username.label }}
            {{ form.username(class="form-input-bubble", placeholder="Username") }}
            {% for error in form.username.errors %}
              <span class="text-danger">{{ error }}</span>
            {% endfor %}
          </div>
          
          <br />
          
          <div class="form-group">
            {{ form.bio.label }}
            {{ form.bio(class="form-input-bubble", placeholder="Enter new bio.") }}
            {% for error in form.bio.errors %}
              <span class="text-danger">{{ error }}</span>
            {% endfor %}
          </div>
          
          <br />
          
          <div class="form-group">
            {{ form.image.label }}
            {{ form.image(class="form-input-bubble") }}
            {% for error in form.image.errors %}
              <span class="text-danger">{{ error }}</span>
            {% endfor %}
          </div>
          
          <br />
          
          <div class="form-group">
            {{ form.submit(class="btn-submit") }}
          </div>
        </form>
        
        <!-- Change Password Form -->
        <form action="{{ url_for('auth.changepassword') }}" method="POST" class="form-edit">
          <div class="form-group">
            <input class="btn-submit" type="submit" value="Change Password"/>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock %}

app/templates/marketplace.html
{% extends "base.html" %}
{% block title %}{{ user.username }}{% endblock %}
{% block content %}

<div class="home">
  <br>
  <div>
    <h1 class="star-text">Welcome to the Marketplace</h1>
    <p class="description">This marketplace is dedicated to selling weapons. <br> <a
        href="{{ url_for('routes.sell') }}">Add Item to Market</a> </p>
  </div>
  <div class="forum-section">
    <div class="post-container">
      <div class="row">
        {% for post in posts %}
        <div class="col-lg-3 col-md-4 col-sm-6">
          <div class="postbubble">
            <img src="{{ url_for('static', filename='/images/sellpics/' + post.img) }}" alt="weapon img">
            <div class="screen-overlay overlay-animation">
              <div class="posttext">
                <div class="posttitle">
                  {{ post.title }}
                  <div class="author">
                    <img src="{{ url_for('static', filename='/images/profilepics/' + post.user.avatar) }}"
                      class="small-avatar" alt="avatar" />
                    {% if post.user.uid != current_user.uid %}
                    <a href="/view-other-userpf/{{ post.user.uid }}">
                      {{ post.user.username }}
                      {% else %}
                      <a href="/profile">
                        {{ post.user.username }}
                        {% endif %}
                      </a>
                  </div>
                </div>
                <div class="postcontent">
                  <p>$<b>{{ post.price }}</b> - {{ post.desc }}</p>
                </div>
              </div>
              <div class="purchase">
                <a href="{{ url_for('routes.purchase', sid=post.sid) }}" class="btn-prominent purchase-btn center">
                  Purchase
                </a>
              </div>
            </div>
          </div>
        </div>
        {% endfor %}
      </div>
    </div>
  </div>
</div>
{% endblock %}

app/templates/ranking.html
{% extends "base.html" %}
{% block title %}Ranking{% endblock %}
{% block content %}
<div class="lb-container">
    <h1 class="pagetitle">Leaderboard</h1>
</div>
<div class="home">
    <div class="lb">
        <div class="lb-border"></div>
        <div class="lb-content">
            <div class="center">Rank</div>
            <div>Profile Picture</div>
            <div class="center">Username</div>
            <div class="center">Email</div>
            <div class="center">Promotions</div>
        </div>
    </div>
    <br>
    <!-- Loop through users and display their info -->
    {% for person in highest_promoted %}
    <div class="lb">
        <div class="lb-border"></div>
        <div class="lb-content">
            <div class="center">{{ loop.index }}</div>
            <div>
                <img
                    class="small-avatar"
                    src="{{ url_for('static', filename='images/profilepics/' ~ person.avatar) }}"
                    alt="Profile Picture"
                    width="50"
                    height="50">
            </div>
            <div class="center">
                {% if person.uid == current_user.uid %}
                <a href="{{ url_for('routes.profile') }}">{{ person.username }}</a>
                {% else %}
                <a href="{{ url_for('routes.view_userpf', user_id=person.uid) }}">{{ person.username }}</a>
                {% endif %}
            </div>
            <div class="center">{{ person.email }}</div>
            <div class="center">{{ person.promote }}</div>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}

app/templates/view-other-userpf.html
{% extends "base.html" %} {% block title %}{{ user.username }}{% endblock %} {%
block content %}
<div class="intro-section">
    <div class="custom-container">
        <div class="profile-header">
            <img src="../static/images/profileheader.jpg" alt="profile-header" />
            <div class="profile-combine">
                <div class="profile-pic-container">
                    <div class="profile-pic">
                        <img src="../static/images/profilepics/{{ user.avatar }}" class="avatar" alt="avatar" />
                    </div>
                </div>
                <div class="profile-details">
                    <div class="responsive-header">
                        <img src="../static/images/ranks/{{ user.rank }}.png" class="rank-img responsive-img" />
                        {{ userinfo.username }}
                    </div>
                    <div class="promotion">
                        {% if not promoted_by_current_user %}
                        <button id="updateButton" class="updateButton btn-prominent"
                            onclick="toggleUpdate(this, {{ userinfo.uid }})">Promote
                            Me</button>
                        {% else %}
                        <button id="updateButton" class="updateButton btn-prominent"
                            onclick="toggleUpdate(this, {{ userinfo.uid }})">Promoted</button>
                        {% endif %}
                    </div>
                </div>
            </div>
            <div class="profile-header-base"></div>
        </div>
        <div>
            <div class="profile-box3">
                <br />
                <div class="desc-box">
                    <p class="responsive-header">{{ userinfo.bio }}</p>
                </div>
                <div class="count-box">
                    <p class="description">
                        Posts: {{ num_posts }}
                    </p>
                    <p class="description">
                        Likes: {{ total_likes }}
                    </p>
                    <p class="description">
                        Promotions: <span id="promotionCount">{{ userinfo.promote }}</span> 
                    </p>
                </div>
            </div>
        </div>
        <div class="select-view">
            <button class="view-button" onclick="openTab(event, 'Posts')" id="defaultOpen">
                Posts
            </button>
            <button class="view-button" onclick="openTab(event, 'Purchased')">
                Purchased
            </button>
            <button class="view-button" onclick="openTab(event, 'Bounties Claimed')">
                Bounties Claimed
            </button>
            <button class="view-button" onclick="openTab(event, 'Listings')">
                Listings
            </button>
        </div>
        <br>

        <!-- Tab content -->
        <div id="Posts" class="tabcontent">
            <div class="forum-section">
                <div class="post-container">
                    <div class="row">
                        {% for item in disc_posts %}
                        <div class="col-lg-3 col-md-4 col-sm-6">
                            <div class="postbubble">
                                <img src="{{ url_for('static', filename='/images/posts/' + item.img) }}"
                                    alt="Post Image">
                                <div class="screen-overlay overlay-animation">
                                    <div class="posttext">
                                        <div class="postheader">
                                            <div class="posttitle">{{ item.title }}</div>
                                            <form
                                                action="{{ url_for('routes.delete_post', post_id=item.pid, post_flag=item.flag) }}"
                                                method="POST">
                                                <input type="hidden" name="_method" value="DELETE">
                                                <button type="submit" class="reactbutton">
                                                    <i class="fa fa-trash fa-lg" aria-hidden="true"></i>
                                                </button>
                                            </form>
                                        </div>
                                        <div class="postcontent">{{ item.desc }}</div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>

        <div id="Purchased" class="tabcontent" style="display: none">
            <h3 style="text-align: center">Purchased Posts~</h3>
            <div class="forum-section">
                <div class="post-container">
                    <div class="row">
                        {% for item in purchased_items %}
                        <div class="col-lg-3 col-md-4 col-sm-6">
                            <div class="postbubble">
                                <img src="{{ url_for('static', filename='images/sellpics/' + item.img) }}"
                                    alt="Post Image">
                                <div class="screen-overlay overlay-animation">
                                    <div class="posttext">
                                        <div class="postheader">
                                            <div class="posttitle">{{ item.title }}</div>
                                        </div>
                                        <div class="postcontent">${{ item.price }}</div>
                                        <div class="postcontent">
                                            {% if item.user.uid != current_user.uid %}
                                            <a href="{{ url_for('routes.view_userpf', user_id=item.user.uid) }}"> Sold
                                                by {{ item.user.username }}</a>
                                            {% else %}
                                            <a href="{{ url_for('routes.profile') }}"> Sold by {{ item.user.username
                                                }}</a>
                                            {% endif %}
                                        </div>
                                        <div class="postcontent">{{ item.desc }}</div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>

        <div id="Bounties-Claimed" class="tabcontent" style="display: none">
            <h3 style="text-align: center">Bounties Claimed</h3>
            <div class="forum-section">
                <div class="post-container">
                    <div class="row">
                        {% for item in bounties_claimed %}
                        <div class="col-lg-3 col-md-4 col-sm-6">
                            <div class="postbubble">
                                <img src="{{ url_for('static', filename='/images/sellpics/' + item.img) }}"
                                    alt="Post Image">
                                <div class="screen-overlay overlay-animation">
                                    <div class="posttext">
                                        <div class="postheader">
                                            <div class="posttitle">{{ item.title }}</div>
                                        </div>
                                        <div class="postcontent">{{ item.desc }}</div>
                                        <div class="postdetails">
                                            <p>Price: {{ item.price }}</p>
                                            <p>Status: {{ item.status }}</p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>

        <div id="Listings" class="tabcontent" style="display: none">
            <h3 style="text-align: center">Listings~</h3>
            <div class="forum-section">
                <div class="post-container">
                    <div class="row">
                        {% for item in sold_items %}
                        <div class="col-lg-3 col-md-4 col-sm-6">
                            <div class="postbubble">
                                {% if item.flag == "Listing"%}
                                <img src="{{ url_for('static', filename='images/sellpics/' + item.img) }}"
                                    alt="Post Image">
                                {% elif item.flag == "Bounty" %}
                                <img src="{{ url_for('static', filename='images/posts/' + item.img) }}"
                                    alt="Post Image">
                                {% endif %}
                                <div class="screen-overlay overlay-animation">
                                    <div class="posttext">
                                        <div class="postheader">
                                            <div class="posttitle">{{ item.title }}</div>
                                            <form
                                                action="{{ url_for('routes.delete_post', post_id=item.sid if item.flag == 'Listing' else item.pid, post_flag=item.flag) }}"
                                                method="POST">
                                                <input type="hidden" name="_method" value="DELETE">
                                                <button type="submit" class="reactbutton">
                                                    <i class="fa fa-trash fa-lg" aria-hidden="true"></i>
                                                </button>
                                            </form>
                                        </div>
                                        <div class="postcontent">{{ item.desc }}</div>
                                        <div class="postdetails">
                                            <p>Price: {{ item.price }}</p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </div>
    <br>
</div>
</div>
{% endblock %}